language: node_js
node_js: '11'
cache: yarn
env:
  global:
    - FORCE_COLOR=1
jobs:
  include:
    - stage: test
      script:
        - yarn run prettier
        - yarn run tslint
        - yarn run build
        - yarn test
        - 'bash <(curl -s https://codecov.io/bash)'
stages:
  - test
branches:
  only:
    - master
